DEFAULTS = [
    ("font", "sans", "Font of the text"),
    ("fontsize", None, "Font pixel size. Calculated if None."),
    ("fontcolor", "ffffff", "Text color"),
    ("icon_size", 16, "Size of the window icons"),
    ("icon_spacing_left", 0, "Spacing to the left of the icons"),
    ("icon_spacing_right", 8, "Spacing to the right of the icons"),
    ("icon_alignment", "center", "Alignment of the icons (left/center/right)"),
    ("padding_left", 0, "Padding on the left side"),
    ("padding_right", 0, "Padding on the right side"),
    ("margin_x", -20, "Margin on the X axis"),
    ("theme_mode", "preferred", "Icon theme mode (preferred or fallback)"),
    ("theme_path", None, "Path to the icon theme"),
    ("background_inactive", "334455", "Background color for inactive groups"),
    ("background_active", "005577", "Background color for active group"),
    ("background_empty", "333344", "Background color for empty groups"),
    ("fallback_icon", "/home/cadr/.config/qtile/unk.png", "Path to the fallback icon"),
    ("max_width", 135, "Maximum width of the widget"),
    ("min_width", 135, "Minimum width of the widget"),
    ("label_visibility", "None", "Visibility of the label (Always/Empty/None)"),
    ("label_position", "Center", "Position of the label (Left/Center)"),
    ("line_thickness_active", 1, "Thickness of the line under the active window"),
    ("line_thickness_inactive", 1, "Thickness of the line under the inactive window"),
    ("line_thickness_floating", 1, "Thickness of the line under the floating window"),
    ("line_thickness_minimized", 1, "Thickness of the line under the minimized window"),
    ("line_color_active", "00FF00", "Color of the line under the active window"),
    ("line_color_inactive", "000000", "Color of the line under the inactive window"),
    ("line_color_floating", "FF0000", "Color of the line under the floating window"),
    ("line_color_minimized", "FFFF00", "Color of the line under the minimized window"),
    ("line_offset", 5, "Offset of the line from the bottom of the icon"),
    ("scroll_groups", ['1', '2', '3', '4'], "List of groups to scroll through"),
]
